### ISSUE TITLE
Eclipse build error

### ISSUE THREAD

**Issue by djewiss** [mwaylabs/fruitymesh-devenv#1]
Hi There

This is awesome, thank you! I am getting the following error when I try to build-

"make: **\* No rule to make target 'C:/nrf/sdk/nrf_sdk_8_1/components/ble/ble_radio_notification/ble_radio_notification.c', needed by 'src/nrf/ble_radio_notification.o'.  Stop. FruityMesh          C/C++ Problem"

I don't suppose you would know how I could fix this?

Thx Darryl

**Comment by mariusheil** [comment]
Hi,

I was just wondering why you are compiling against the SDK 8.1, but then I've noticed that I've made a mistake in the build environment. Go under fruitymesh\src\nrf\ and correct the path to ble_radio_notification.c
It is still pointing to the old sdk but should instead be pointing at nrf_sdk_latest to avoid these issues. I'll fix this in a few minutes

**Comment by mariusheil** [comment]
I've fixed it, you have to pull the fruitymesh repository again.
If everything works for you, I'd be glad if you could give some feedback how hard or easy the setup process was :-)
