### ISSUE TITLE
Error: impossible constraint in 'asm'

### ISSUE THREAD

**Issue by djewiss** [mwaylabs/fruitymesh-devenv#2]
Hi There

I am getting the following errors -
impossible constraint in 'asm'  FruityMesh      line 1348, external location: c:\nrf\sdk\ehal_latest\arm\nordic\nrf51\nrf51_sdk\components\softdevice\s130\headers\ble_gap.h    C/C++ Problem
lto-wrapper failed  FruityMesh          C/C++ Problem
make: **\* [FruityMesh.elf] Error 1  FruityMesh          C/C++ Problem
recipe for target 'FruityMesh.elf' failed   makefile    /FruityMesh/Debug   line 63 C/C++ Problem

Would be able to help me fix this?

Thx Darryl

**Comment by mariusheil** [comment]
Hi,

i think I can help you, that was my fault, I forgot an important step in the tutorial. I've just updated the readme, you have to edit one of the SDK files so that it compiles.

**Comment by djewiss** [comment]
Fixed it, thanks!
