### ISSUE TITLE
Cannot open eclipse

### ISSUE THREAD

**Issue by junaediadi** [mwaylabs/fruitymesh-devenv#5]
Hello All,

I have followed the tutorial to instal fruity mesh using eclipse.However,when I open eclipse,the notification "an error has occured,see the log null" appear. Am i wrong when following the tutorial?

**Comment by mariusheil** [comment]
So, does it not compile? I haven't had this error, but It looks a little
like an eclipse bug. Have you tried to use this eclipse environment here:
https://github.com/mwaylabs/fruitymesh-devenv or did you try to set it up
on your own?

2016-02-19 1:35 GMT+01:00 junaediadi notifications@github.com:

**Comment by junaediadi** [comment]
Dear MariusHeil,
I'm a student at Offenburg Univeristy Germany and I think your project is great because before that I used CSR and hit the brick due to closed library.

I used that eclipse from repository.. It works now but I must delete inside the folder workspace and then I import the project again.

How to compile that,is it use the run - external tools?

What about If I only used NRF51DK without dongle? Can I send the command directly from the NRF51 DK? Because I still order the device now.

**Comment by mariusheil** [comment]
Hello,

greetings from Stuttgart, then ;-)
First, you have to build the project (Right click on Project => Build
Project) if that works: Compiling, Linking, etc,... then you're almost
there. All you have to do next is to flash it on a Beacon. This works by
running the deploy script from the tools for example (Current - Debug =>
Flashes the current Debug build on all available Beacons).

Devboard works as well, and should run out of the Box. Does have no LED
colours, though. You could also use nRFgo Studio to flash the Softdevice
and the generated .hex file from the Debug folder.

I'll be on holidays for a week, but I might find the time to answer mails
after each day of skiing :D

Good luck

2016-02-19 12:39 GMT+01:00 junaediadi notifications@github.com:

**Comment by junaediadi** [comment]
Greeting too From Offenburg. :D

I tried to build that but it is not working.I only can do run->external tools.
I will try to restart from beginning again to build using eclipse.

Have a nice holiday and thanks from your help.:D

**Comment by junaediadi** [comment]
Dear Marius,

I have this problem when first compiled using eclipse:
"An internal error occurred during: "Computing Git status for repository FruityMesh".
Should not get here"
16:08:33 ***\* Incremental Build of configuration Debug for project FruityMesh ****
make all 
Cannot run program "make": Launching failed

Error: Program "make" not found in PATH
PATH=[C:\nrf\sdk\gcc_arm_embedded_4_9\bin;C:\NordicGCC\BuildTools\bin;C:\NordicGCC\GCC\bin;%PATH%]
16:08:34 Build Finished (took 533ms)"

could you help me?

**Comment by mariusheil** [comment]
I think yes,

the make executable does not exist in the given Path. I guess that is a
mistake that I made when setting up the eclipse installation. You can edit
the Path under Project Properties => C/C++ Build => Environment => PATH.
You have to insert the path to the installation directory of the GNU ARM
Eclipse Build tools. (do a windows search for "make", if you don't have it,
install the Gnu arm eclipse build tools)

2016-02-19 16:10 GMT+01:00 junaediadi notifications@github.com:

**Comment by junaediadi** [comment]
Thanks..
It works and I can build the project,but with error message dialog.
"An internal error occurred during: "Computing Git status for repository FruityMesh".
Should not get here".However, I think that it is still okay.

arm-none-eabi-objcopy -O binary FruityMesh.elf FruityMesh.bin;  md5 -p < FruityMesh.bin > FruityMeshmd5.bin; cp FruityMeshmd5.bin firmware.bin
c:/program files/gnu arm eclipse/build tools/2.6-201507152002/bin/sh: md5: not found

Invoking: Cross ARM GNU Create Flash Image
arm-none-eabi-objcopy -O ihex "FruityMesh.elf"  "FruityMesh.hex"
Finished building: FruityMesh.hex

Invoking: Cross ARM GNU Print Size
arm-none-eabi-size --format=berkeley --totals --radix=10 "FruityMesh.elf"
   text    data     bss     dec     hex filename
  86759     344    3444   90547   161b3 FruityMesh.elf
  86759     344    3444   90547   161b3 (TOTALS)
Finished building: FruityMesh.siz

16:52:31 Build Finished (took 1m:15s.403ms)

**Comment by mariusheil** [comment]
yes, looks fine to me :-)

2016-02-19 16:58 GMT+01:00 junaediadi notifications@github.com:

**Comment by junaediadi** [comment]
Danke für ihre Hilfe. Ich werde den Code studieren, während die NRF51 Bord wartet.:D
Viele Gruße
